import Sidebar from "@/components/Sidebar/Sidebar";
import "../globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Manrope } from "next/font/google";
import Menu from "@/components/MobileMenu/Menu";

export const metadata = {
  title: "Sahana Eden | Dashboard",
  description: "Generated by Next.js",
};

const manrope = Manrope({subsets: ["latin"]})

export default function RootLayout({ children }) {
  return (
        <html>
          <body className={manrope.className}>
            <div className="mainContainer">
            <Sidebar />
            <Navbar />
            <main className="contentContainer">{children}</main>
            <Menu />
          </div>
        </body>
        </html>
  );
}
